/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADSI
 */
public class T4ejercicio5 extends javax.swing.JFrame {

    
    int a,b;
    /**
     * Creates new form T4ejercicio5
     */
    public T4ejercicio5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Perro = new javax.swing.JButton();
        Gato = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Seleccione su Voto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(188, 38, 157, 29);

        Perro.setForeground(new java.awt.Color(255, 0, 0));
        Perro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perro-listo.jpg"))); // NOI18N
        Perro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerroActionPerformed(evt);
            }
        });
        getContentPane().add(Perro);
        Perro.setBounds(81, 112, 227, 134);

        Gato.setBackground(new java.awt.Color(255, 255, 255));
        Gato.setForeground(new java.awt.Color(255, 0, 0));
        Gato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gato.jpg"))); // NOI18N
        Gato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GatoActionPerformed(evt);
            }
        });
        getContentPane().add(Gato);
        Gato.setBounds(326, 112, 231, 134);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar);
        Limpiar.setBounds(81, 289, 109, 23);

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular);
        Calcular.setBounds(370, 289, 116, 23);

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(81, 356, 476, 96);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GatoActionPerformed

        b++;
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_GatoActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed


        if(a>b){
        
        
        Salida.setText(" El partido Ganador fue Perro con " +a+ " Votos");
        }
        
        else{
        Salida.setText(" El partido Ganador fue Gato con " +b+ " Votos");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularActionPerformed

    private void PerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerroActionPerformed

        a++;

        // TODO add your handling code here:
    }//GEN-LAST:event_PerroActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed

        b=0;
        a=0;
        Salida.setText(null);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T4ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T4ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T4ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T4ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T4ejercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Gato;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Perro;
    private javax.swing.JTextArea Salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
